---
# Per environment values which override defaults in hmpps-breach-report-co-sso-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: breach-report-co-sso-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://breach-report-co-sso-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    COSSO_API_URL: "https://breach-report-co-sso-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - moj_cloud_platform # for end-to-end testing

generic-prometheus-alerts:
  alertSeverity: hmpps-co-sso-notifications
